mkdir _lighthouse-report-queue/1091
lighthouse https://www.insureyourtoy.com/ --quiet --chrome-flags="--headless" --output json --output-path _lighthouse-report-queue/1091/insureyourtoy.com_.json &
lighthouse https://www.insureyourtoy.com/blog --quiet --chrome-flags="--headless" --output json --output-path _lighthouse-report-queue/1091/insureyourtoy.com_blog.json &
lighthouse https://www.insureyourtoy.com/woodstock-ga-auto-insurance.html --quiet --chrome-flags="--headless" --output json --output-path _lighthouse-report-queue/1091/insureyourtoy.com_woodstock-ga-auto-insurance.html.json &
lighthouse https://www.insureyourtoy.com/woodstock-ga-home-insurance.html --quiet --chrome-flags="--headless" --output json --output-path _lighthouse-report-queue/1091/insureyourtoy.com_woodstock-ga-home-insurance.html.json &
lighthouse https://www.insureyourtoy.com/woodstock-ga-commercial-auto-insurance.html --quiet --chrome-flags="--headless" --output json --output-path _lighthouse-report-queue/1091/insureyourtoy.com_woodstock-ga-commercial-auto-insurance.html.json &
lighthouse https://www.insureyourtoy.com/boat-less-than-35-feet.html --quiet --chrome-flags="--headless" --output json --output-path _lighthouse-report-queue/1091/insureyourtoy.com_boat-less-than-35-feet.html.json
lighthouse https://www.insureyourtoy.com/woodstock-ga-motorcycle-insurance.html --quiet --chrome-flags="--headless" --output json --output-path _lighthouse-report-queue/1091/insureyourtoy.com_woodstock-ga-motorcycle-insurance.html.json &
lighthouse https://www.insureyourtoy.com/woodstock-ga-rv-insurance.html --quiet --chrome-flags="--headless" --output json --output-path _lighthouse-report-queue/1091/insureyourtoy.com_woodstock-ga-rv-insurance.html.json &
lighthouse https://www.insureyourtoy.com/woodstock-ga-pet-insurance.html --quiet --chrome-flags="--headless" --output json --output-path _lighthouse-report-queue/1091/insureyourtoy.com_woodstock-ga-pet-insurance.html.json &
lighthouse https://www.insureyourtoy.com/woodstock-ga-life-insurance.html --quiet --chrome-flags="--headless" --output json --output-path _lighthouse-report-queue/1091/insureyourtoy.com_woodstock-ga-life-insurance.html.json &
lighthouse https://www.insureyourtoy.com/woodstock-ga-golf-cart-insurance.html --quiet --chrome-flags="--headless" --output json --output-path _lighthouse-report-queue/1091/insureyourtoy.com_woodstock-ga-golf-cart-insurance.html.json
lighthouse https://www.insureyourtoy.com/contest.html --quiet --chrome-flags="--headless" --output json --output-path _lighthouse-report-queue/1091/insureyourtoy.com_contest.html.json &
lighthouse https://www.insureyourtoy.com/contact-us.html --quiet --chrome-flags="--headless" --output json --output-path _lighthouse-report-queue/1091/insureyourtoy.com_contact-us.html.json &
lighthouse https://www.insureyourtoy.com/file-a-claim-carriers.html --quiet --chrome-flags="--headless" --output json --output-path _lighthouse-report-queue/1091/insureyourtoy.com_file-a-claim-carriers.html.json &
lighthouse https://www.insureyourtoy.com/make-a-payment-carriers.html --quiet --chrome-flags="--headless" --output json --output-path _lighthouse-report-queue/1091/insureyourtoy.com_make-a-payment-carriers.html.json &